// src/components/mdx/header-docs.tsx
import { Separator } from "@/components/ui/separator";

interface HeaderDocsProps {
  title: string;
  description: string;
}

export function HeaderDocs({ title, description }: HeaderDocsProps) {
  return (
    <>
      <h1 className="scroll-m-20 text-4xl font-semibold tracking-tight sm:text-3xl xl:text-4xl text-foreground">
        {title}
      </h1>
      <p className="text-muted-foreground text-[1.05rem] sm:text-base">
        {description}
      </p>
      <Separator />
    </>
  );
}

// src/components/ui/markdown-components/HeaderDocs.vue
<script setup lang="ts">
import { Separator } from "../separator";

defineProps<{
  title: string;
  description: string;
}>();
</script>

<template>
  <h1
    class="scroll-m-20 text-4xl font-semibold tracking-tight sm:text-3xl xl:text-4xl text-foreground"
  >
    {{ title }}
  </h1>
  <p class="text-muted-foreground text-[1.05rem] sm:text-base">
    {{ description }}
  </p>
  <Separator />
</template>
