// src/components/button-theme.tsx
import { Button } from "@/components/ui/button";
import { Moon, Sun } from "lucide-react";

interface ButtonThemeProps {
  isDark: boolean;
  onClick: () => void;
}

export function ButtonTheme({ isDark, onClick }: ButtonThemeProps) {
  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={onClick}
      aria-label="Toggle dark mode"
    >
      {isDark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
    </Button>
  );
}

// src/components/home/ButtonTheme.vue
<script setup lang="ts">
import { Button } from "../ui/button";
import { Moon, Sun } from "lucide-vue-next";

defineProps<{
  isDark: boolean;
}>();

const emit = defineEmits<{
  (e: "click"): void;
}>();

function toggleDarkMode() {
  emit("click");
}
</script>
<template>
  <Button
    variant="ghost"
    size="icon"
    @click="toggleDarkMode"
    aria-label="Toggle dark mode"
  >
    <Sun v-if="isDark" class="w-4 h-4" />
    <Moon v-else class="w-4 h-4" />
  </Button>
</template>
